apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: jenkins
  labels: 
    name: jenkins
spec: 
  replicas: 1
  template: 
    metadata: 
      name: jenkins
      labels: 
        name: jenkins
    spec: 
      containers: 
        - name: jenkins
          image: jenkins:demo
          imagePullPolicy: Never
          ports: 
            - containerPort: 8080
            - containerPort: 50000
          env:
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false -Djenkins.useSecurity=false"
          volumeMounts: 
            - name: jenkins-data
              mountPath: /var/jenkins_home
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 5
      volumes: 
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins
