---
apiVersion: v1
kind: Service
metadata: 
  name: jenkins
spec: 
  type: NodePort
  selector: 
    name: jenkins
  ports: 
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: agent
      port: 50000
      protocol: TCP
